In [3]:
import pandas as pd

df = pd.read_json("../data/sample/StreamingHistory_music_0.json")
df.head()

            endTime   artistName        trackName  msPlayed
0  2025-10-18 17:58  Drosa 99 39  Stadt kreis 238    169929
1  2025-10-18 18:06   Vori MC 20    Zeit blau 997    244054
2  2025-10-18 23:02   Vori MC 20    Zeit blau 997    247006
3  2025-10-19 10:31  Drosa 99 39  Stadt kreis 238    168944
4  2025-10-19 13:01     Drosa 21  Signal herz 346    175073

In [4]:
df.shape

(8950, 4)

In [5]:
df["song_id"] = df["artistName"] + " - " + df["trackName"]
df.head()

,endTime,artistName,trackName,msPlayed,song_id
0,2025-10-18 17:58,Drosa 99 39,Stadt kreis 238,169929,Drosa 99 39 - Stadt kreis 238
1,2025-10-18 18:06,Vori MC 20,Zeit blau 997,244054,Vori MC 20 - Zeit blau 997
2,2025-10-18 23:02,Vori MC 20,Zeit blau 997,247006,Vori MC 20 - Zeit blau 997
3,2025-10-19 10:31,Drosa 99 39,Stadt kreis 238,168944,Drosa 99 39 - Stadt kreis 238
4,2025-10-19 13:01,Drosa 21,Signal herz 346,175073,Drosa 21 - Signal herz 346

In [6]:
df["song_id"].value_counts()

song_id
Votex 56 - Blau nacht 374        55
Texlu 38 - Wind wind 818         51
Vojux 26 - Signal wellen 1145    49
Voka 99 9 - Nacht wind 1077      49
Drosa 99 39 - Herz wind 1053     49
                                 ..
Blysa MC 45 - Echo wellen 628     1
Sari 14 - Glas gold 98            1
Nazé 99 17 - Feuer wellen 184     1
Voka 99 9 - Zeit zeit 695         1
Roka 0 - Sommer stadt 590         1
Name: count, Length: 1138, dtype: int64

In [7]:
df["gehoert"] = df["msPlayed"] >= 30000
df.head(10)

,endTime,artistName,trackName,msPlayed,song_id,gehoert
0,2025-10-18 17:58,Drosa 99 39,Stadt kreis 238,169929,Drosa 99 39 - Stadt kreis 238,True
1,2025-10-18 18:06,Vori MC 20,Zeit blau 997,244054,Vori MC 20 - Zeit blau 997,True
2,2025-10-18 23:02,Vori MC 20,Zeit blau 997,247006,Vori MC 20 - Zeit blau 997,True
3,2025-10-19 10:31,Drosa 99 39,Stadt kreis 238,168944,Drosa 99 39 - Stadt kreis 238,True
4,2025-10-19 13:01,Drosa 21,Signal herz 346,175073,Drosa 21 - Signal herz 346,True
5,2025-10-19 14:43,Texdro 41,Herz nacht 1139,177374,Texdro 41 - Herz nacht 1139,True
6,2025-10-19 16:49,Vori MC 20,Zeit blau 997,245283,Vori MC 20 - Zeit blau 997,True
7,2025-10-19 17:55,Drosa 21,Signal herz 346,24180,Drosa 21 - Signal herz 346,False
8,2025-10-19 18:28,Vori MC 20,Zeit blau 997,244107,Vori MC 20 - Zeit blau 997,True
9,2025-10-20 12:15,Mosax 29,Blau wellen 555,17084,Mosax 29 - Blau wellen 555,False

In [ ]:
df["gehoert"].value_counts()

gehoert
True     7504
False    1446
Name: count, dtype: int64

In [9]:
geskippt = df[df["gehoert"] == False]
geskippt.head()

,endTime,artistName,trackName,msPlayed,song_id,gehoert
7,2025-10-19 17:55,Drosa 21,Signal herz 346,24180,Drosa 21 - Signal herz 346,False
9,2025-10-20 12:15,Mosax 29,Blau wellen 555,17084,Mosax 29 - Blau wellen 555,False
11,2025-10-20 18:19,Texdro 41,Herz nacht 1139,28463,Texdro 41 - Herz nacht 1139,False
19,2025-10-21 23:18,Nazé 99 17,Kreis neon 715,15964,Nazé 99 17 - Kreis neon 715,False
21,2025-10-22 11:53,Naka 99 33,Mond herz 837,9881,Naka 99 33 - Mond herz 837,False

In [10]:
song = df[df["song_id"] == "Votex 56 - Blau nacht 374"]
song

,endTime,artistName,trackName,msPlayed,song_id,gehoert
5102,2026-05-17 17:49,Votex 56,Blau nacht 374,16466,Votex 56 - Blau nacht 374,False
5107,2026-05-17 18:18,Votex 56,Blau nacht 374,220744,Votex 56 - Blau nacht 374,True
5138,2026-05-18 18:05,Votex 56,Blau nacht 374,222102,Votex 56 - Blau nacht 374,True
5139,2026-05-18 18:56,Votex 56,Blau nacht 374,219378,Votex 56 - Blau nacht 374,True
5150,2026-05-19 11:29,Votex 56,Blau nacht 374,10042,Votex 56 - Blau nacht 374,False
5158,2026-05-19 13:46,Votex 56,Blau nacht 374,221108,Votex 56 - Blau nacht 374,True
5159,2026-05-19 14:16,Votex 56,Blau nacht 374,220780,Votex 56 - Blau nacht 374,True
5184,2026-05-19 23:21,Votex 56,Blau nacht 374,222458,Votex 56 - Blau nacht 374,True
5200,2026-05-20 17:13,Votex 56,Blau nacht 374,6195,Votex 56 - Blau nacht 374,False
5214,2026-05-21 11:08,Votex 56,Blau nacht 374,218089,Votex 56 - Blau nacht 374,True
5218,2026-05-21 14:25,Votex 56,Blau nacht 374,220453,Votex 56 - Blau nacht 374,True
5225,2026-05-21 18:17,Votex 56,Blau nacht 374,220670,Votex 56 - Blau nacht 374,True
5231,2026-05-21 21:02,Votex 56,Blau nacht 374,221877,Votex 56 - Blau nacht 374,True
5266,2026-05-23 13:08,Votex 56,Blau nacht 374,217704,Votex 56 - Blau nacht 374,True
5278,2026-05-23 18:01,Votex 56,Blau nacht 374,220875,Votex 56 - Blau nacht 374,True
5289,2026-05-24 11:08,Votex 56,Blau nacht 374,17755,Votex 56 - Blau nacht 374,False
5322,2026-05-25 17:00,Votex 56,Blau nacht 374,218267,Votex 56 - Blau nacht 374,True
5327,2026-05-25 19:22,Votex 56,Blau nacht 374,217709,Votex 56 - Blau nacht 374,True
5329,2026-05-25 19:44,Votex 56,Blau nacht 374,220039,Votex 56 - Blau nacht 374,True
5348,2026-05-27 09:27,Votex 56,Blau nacht 374,219008,Votex 56 - Blau nacht 374,True
5360,2026-05-27 22:47,Votex 56,Blau nacht 374,220031,Votex 56 - Blau nacht 374,True
5361,2026-05-27 23:46,Votex 56,Blau nacht 374,222017,Votex 56 - Blau nacht 374,True
5368,2026-05-28 16:18,Votex 56,Blau nacht 374,222392,Votex 56 - Blau nacht 374,True
5391,2026-05-29 22:57,Votex 56,Blau nacht 374,219637,Votex 56 - Blau nacht 374,True
5398,2026-05-30 14:07,Votex 56,Blau nacht 374,218584,Votex 56 - Blau nacht 374,True
5399,2026-05-30 14:51,Votex 56,Blau nacht 374,222589,Votex 56 - Blau nacht 374,True
5416,2026-05-31 16:15,Votex 56,Blau nacht 374,3787,Votex 56 - Blau nacht 374,False
5424,2026-05-31 23:55,Votex 56,Blau nacht 374,220184,Votex 56 - Blau nacht 374,True
5445,2026-06-01 20:40,Votex 56,Blau nacht 374,219492,Votex 56 - Blau nacht 374,True
5462,2026-06-02 19:50,Votex 56,Blau nacht 374,219117,Votex 56 - Blau nacht 374,True
5503,2026-06-04 18:03,Votex 56,Blau nacht 374,12627,Votex 56 - Blau nacht 374,False
5589,2026-06-08 12:13,Votex 56,Blau nacht 374,218281,Votex 56 - Blau nacht 374,True
5633,2026-06-09 18:23,Votex 56,Blau nacht 374,220357,Votex 56 - Blau nacht 374,True
5655,2026-06-10 13:03,Votex 56,Blau nacht 374,221091,Votex 56 - Blau nacht 374,True
5672,2026-06-10 19:08,Votex 56,Blau nacht 374,219210,Votex 56 - Blau nacht 374,True
5719,2026-06-12 16:32,Votex 56,Blau nacht 374,221793,Votex 56 - Blau nacht 374,True
5744,2026-06-13 15:11,Votex 56,Blau nacht 374,219613,Votex 56 - Blau nacht 374,True
5811,2026-06-15 16:15,Votex 56,Blau nacht 374,222491,Votex 56 - Blau nacht 374,True
5851,2026-06-17 15:51,Votex 56,Blau nacht 374,219495,Votex 56 - Blau nacht 374,True
5852,2026-06-17 17:16,Votex 56,Blau nacht 374,17183,Votex 56 - Blau nacht 374,False
5863,2026-06-18 12:06,Votex 56,Blau nacht 374,220794,Votex 56 - Blau nacht 374,True
5873,2026-06-18 17:15,Votex 56,Blau nacht 374,218911,Votex 56 - Blau nacht 374,True
5961,2026-06-22 14:32,Votex 56,Blau nacht 374,220271,Votex 56 - Blau nacht 374,True
6038,2026-06-26 11:16,Votex 56,Blau nacht 374,221979,Votex 56 - Blau nacht 374,True
6065,2026-06-27 12:11,Votex 56,Blau nacht 374,222116,Votex 56 - Blau nacht 374,True
6101,2026-06-28 12:49,Votex 56,Blau nacht 374,217788,Votex 56 - Blau nacht 374,True
6121,2026-06-28 20:17,Votex 56,Blau nacht 374,220382,Votex 56 - Blau nacht 374,True
6125,2026-06-29 11:20,Votex 56,Blau nacht 374,221911,Votex 56 - Blau nacht 374,True
6152,2026-06-30 13:53,Votex 56,Blau nacht 374,218324,Votex 56 - Blau nacht 374,True
6178,2026-07-01 14:36,Votex 56,Blau nacht 374,219518,Votex 56 - Blau nacht 374,True
6262,2026-07-03 23:57,Votex 56,Blau nacht 374,217916,Votex 56 - Blau nacht 374,True
6323,2026-07-05 19:35,Votex 56,Blau nacht 374,18616,Votex 56 - Blau nacht 374,False
6333,2026-07-06 13:42,Votex 56,Blau nacht 374,218757,Votex 56 - Blau nacht 374,True
6443,2026-07-10 19:54,Votex 56,Blau nacht 374,221754,Votex 56 - Blau nacht 374,True
6491,2026-07-12 17:27,Votex 56,Blau nacht 374,218258,Votex 56 - Blau nacht 374,True

In [16]:
song = df[df["song_id"] == "Votex 56 - Blau nacht 374"]
song_gehoert = song[song["gehoert"] == True]
df"song_gehoert".value_counts()

SyntaxError: invalid syntax (2982423484.py, line 3)

In [17]:
df["endTime"] = pd.to_datetime(df["endTime"])
df.dtypes

endTime       datetime64[ns]
artistName            object
trackName             object
msPlayed               int64
song_id               object
gehoert                 bool
dtype: object

In [18]:
song = df[df["song_id"] == "Votex 56 - Blau nacht 374"]
erster_play = song["endTime"].min()
erster_play

Timestamp('2026-05-17 17:49:00')

In [19]:
ende_woche = erster_play + pd.Timedelta(days=7)
ende_woche

Timestamp('2026-05-24 17:49:00')

In [20]:
erste_woche = song[(song["endTime"] < ende_woche) & (song["gehoert"] == True)]
len(erste_woche)

12

In [21]:
ende_monat = erster_play + pd.Timedelta(days=30)

In [22]:
erster_monat = song[(song["endTime"] < ende_monat) & (song["gehoert"] == True)]
len(erster_monat)

32

In [31]:
len(erster_monat) >= 10

True

In [43]:
def features_fuer_song(song):
    erster_play = song["endTime"].min()
    ende_woche = erster_play + pd.Timedelta(days=7)
    ende_monat = erster_play + pd.Timedelta(days=30)

    erste_woche = song[(song["endTime"] < ende_woche) & (song["gehoert"] == True)]
    erster_monat = song[(song["endTime"] < ende_monat) & (song["gehoert"] == True)]

    return {
        "first_played_at": erster_play,
        "plays_first_7d": len(erste_woche),
        "is_favorite": len(erster_monat) >= 10,
        "woche_fertig": ende_woche <= ende_daten,
        "label_fertig": ende_monat <= ende_daten,
    }

In [44]:
features_fuer_song(song)

{'first_played_at': Timestamp('2026-09-11 10:39:00'),
 'plays_first_7d': 3,
 'is_favorite': False,
 'woche_fertig': True,
 'label_fertig': True}

In [49]:
anderer_song = df[df["song_id"] == "Naka 99 33 - Mond herz 837"]
features_fuer_song(anderer_song)

{'first_played_at': Timestamp('2025-10-22 11:53:00'),
 'plays_first_7d': 3,
 'is_favorite': False,
 'woche_fertig': True,
 'label_fertig': True}

In [50]:
zeilen = []

for song_id, song in df.groupby("song_id"):
    resultat = features_fuer_song(song)
    resultat["song_id"] = song_id
    zeilen.append(resultat)

features = pd.DataFrame(zeilen)
features.head()

,first_played_at,plays_first_7d,is_favorite,woche_fertig,label_fertig,song_id
0,2026-09-20 20:24:00,1,False,True,False,Blydro 31 - Blau glas 1198
1,2025-11-04 12:10:00,1,False,True,True,Blydro 31 - Blau licht 373
2,2026-07-03 17:32:00,2,False,True,True,Blydro 31 - Blau signal 352
3,2026-07-16 17:47:00,0,False,True,True,Blydro 31 - Echo echo 858
4,2026-07-12 09:35:00,2,False,True,True,Blydro 31 - Echo zeit 888

In [46]:
features.shape

(1138, 4)

In [51]:
features["is_favorite"].value_counts()

is_favorite
False    956
True     182
Name: count, dtype: int64

In [48]:
ende_daten = df["endTime"].max()
ende_daten

Timestamp('2026-10-17 23:49:00')

In [52]:
features.columns

Index(['first_played_at', 'plays_first_7d', 'is_favorite', 'woche_fertig',
       'label_fertig', 'song_id'],
      dtype='object')

In [53]:
  features["label_fertig"].value_counts()

label_fertig
True     1035
False     103
Name: count, dtype: int64

In [54]:
  training = features[features["label_fertig"] == True]
  training.shape

(1035, 6)

In [55]:
  training = features[features["label_fertig"] == True]
  training.shape

(1035, 6)

In [56]:
  training["is_favorite"].value_counts()

is_favorite
False    860
True     175
Name: count, dtype: int64